public class BasicExample1_extension {

    public PageReference Transfer() {
        return null;
    }

    private final Employee__c emp;
    public String Name1{get;set;}
    public String username1{get;set;}
    public String pasword1{get;set;}
    
    public BasicExample1_extension(ApexPages.StandardController controller) {
  

    }
    
    public PageReference getTransfer()
    {
        Return null;
    }

}